feedback:
  max_iterations: 3
  confidence_threshold: 0.7
  retry_delay: 2
  fallback_agent: decomposer
  agent_specific:
    decomposer:
      max_iterations: 5
      confidence_threshold: 0.8
    validator:
      max_iterations: 4
      confidence_threshold: 0.75
    codegen:
      max_iterations: 3
      confidence_threshold: 0.85
    docker:
      max_iterations: 2
      confidence_threshold: 0.9

verification_rules:
  request_validation:
    required_fields: [ is_valid ]
    error_patterns:
      - invalid request
      - not feasible
    success_criteria: "is_valid is true with high confidence"
    priority: 0
    valid_result:
      is_valid: true
      reasons: "optional array of explanations"

  decomposer:
    required_fields: [modules]
    module_fields: [name, input, output, logic, external]
    error_patterns: 
      - предположение
      - неизвестно
      - не указано
    success_criteria: "all fields present and no assumptions in logic"
    priority: 1

  validator:
    required_fields: [status]
    valid_statuses: 
      - approved
      - rejected
    error_patterns: 
      - непонятно
      - ошибка
    success_criteria: "status is 'approved' or 'rejected' with comments"
    priority: 2

  consistency:
    required_fields: [status]
    valid_statuses: 
      - approved
      - rejected
    error_patterns: 
      - противоречие
      - несоответствие
    success_criteria: "status is 'approved' or 'rejected' with inconsistencies"
    priority: 3

  codegen:
    required_fields: null
    error_patterns: 
      - syntax error
      - import error
      - undefined
    success_criteria: "valid Python syntax and dependencies included"
    priority: 4

  extractor:
    required_fields: [file_path]
    error_patterns: 
      - not found
      - invalid path
    success_criteria: "file_path exists and contains valid code"
    priority: 5

  docker:
    required_fields: [dockerfile, compose]
    error_patterns: 
      - build failed
      - invalid dockerfile
    success_criteria: "Dockerfile and docker-compose.yml are valid and buildable"
    priority: 6

  monitor:
    required_fields: [command]
    valid_commands: 
      - none
      - Перезапустить <agent>
      - Принудительный переход к consistency
    error_patterns: 
      - invalid command
    success_criteria: "valid command based on state"
    priority: 9

  knowledge:
    required_fields: null
    error_patterns: 
      - empty
      - no data
    success_criteria: "non-empty list of categorized data"
    priority: 7

  coordinator:
    required_fields: null
    error_patterns: 
      - unknown agent
      - invalid transition
    success_criteria: "returns a valid agent name"
    priority: 8

  tester:
    required_fields: [tests]
    error_patterns: 
      - pytest error
      - test failed
    success_criteria: "valid pytest code covering key functionality"
    priority: 10

  docs:
    required_fields: null
    error_patterns: 
      - missing usage
      - no documentation
    success_criteria: "README.md contains interfaces and usage instructions"
    priority: 11
